import type { Outcome, Result } from "./model.js";

const outcomes: readonly Outcome[] = [
  "demonstrated",
  "accepted-unverified",
  "unsupported",
  "rejected-valid",
  "invalid-rejected",
  "invalid-accepted",
  "invalid-blocked",
  "failed",
  "untested",
];
export function summary(results: readonly Result[]): Record<Outcome, number> {
  return Object.fromEntries(
    outcomes.map((outcome) => [outcome, results.filter((r) => r.outcome === outcome).length]),
  ) as Record<Outcome, number>;
}
export function strictFailure(results: readonly Result[]): boolean {
  return results.some((r) => r.outcome !== "demonstrated" && r.outcome !== "invalid-rejected");
}
const cell = (text: string) =>
  text.replaceAll("|", "\\|").replaceAll("\n", " ").replaceAll("<", "&lt;").replaceAll(">", "&gt;");

export function render(results: readonly Result[]): string {
  const rows = [
    "# Conformance coverage report",
    "",
    "Generated by `pnpm conformance --write`. Do not edit by hand. Machine-readable results: [results.json](../conformance/results.json). Method, upstream sources, limitations, and contribution instructions: [conformance/README.md](../conformance/README.md).",
    "",
    "**This is a compatibility and gap inventory, not certification or full specification conformance.** An expected rejection remains a missing feature. Acceptance does not establish correct behavior. Counts describe these cases only; they are not a percentage of any specification.",
    "",
    `Catalog: **${results.length} cases**. All execution is offline; no upstream SOAP endpoint is contacted.`,
    "",
    "| Outcome | Count |",
    "| --- | ---: |",
    ...Object.entries(summary(results)).map(([status, count]) => `| ${status} | ${count} |`),
    "",
    "`demonstrated`: the case's stated behavioral assertions passed, together with generation and client/HttpApi construction. Upstream cases use decode/re-encode consistency and XML topology, not an independent native-value oracle. `accepted-unverified`: construction only. `unsupported`: explicit unsupported-feature diagnostic. `rejected-valid`: valid input rejected for another reason. `invalid-rejected`: invalid contract rejected during loading/resolution. `invalid-accepted`: invalid contract escaped that validation. `invalid-blocked`: an unsupported feature prevented validity testing. `failed`: acceptance followed by an assertion or construction failure. `untested`: no executable oracle or unavailable upstream resources.",
    "",
    "## Other rejections, validation defects, and behavior failures",
    "",
  ];
  const defects = results.filter((r) =>
    ["invalid-accepted", "failed", "rejected-valid"].includes(r.outcome),
  );
  rows.push("| Case | Outcome | Evidence / first failure |", "| --- | --- | --- |");
  for (const result of defects) {
    const failure = Object.entries(result.phases).find(
      ([, p]) => !["pass", "not-run"].includes(p.status),
    );
    rows.push(
      `| ${result.id} | ${result.outcome} | ${cell(failure ? `${failure[0]}: ${failure[1].detail}` : "Invalid contract accepted by load/resolution; see specification link in inventory")} |`,
    );
  }
  for (const area of [...new Set(results.map((r) => r.area))]) {
    rows.push(
      "",
      `## ${area}`,
      "",
      "| Case / specification | Outcome | Load | Generate | Runtime | HttpApi | Behavior |",
      "| --- | --- | --- | --- | --- | --- | --- |",
    );
    for (const r of results.filter((r) => r.area === area)) {
      rows.push(
        `| [${cell(r.id)}: ${cell(r.title)}](${r.reference}) | ${r.outcome} | ${Object.values(
          r.phases,
        )
          .map((p) => p.status)
          .join(" | ")} |`,
      );
    }
  }
  rows.push(
    "",
    "## Missing features and untested areas",
    "",
    "Exact rejection diagnostics and per-case evidence are in results.json. These results are grouped by the first encountered blocker; resolving it may reveal additional gaps. Untested rows are retained in the catalog and cannot count as passes.",
    "",
  );
  for (const r of results.filter((r) => r.outcome === "untested"))
    rows.push(`- **${r.id}**: ${cell(r.evidence)}`);
  rows.push("");
  return rows.join("\n");
}
